CREATE DATABASE YOUTILITY

CREATE TABLE CLIENTE
(
	IdCliente VARCHAR(128) PRIMARY KEY,
	Nome VARCHAR(128),
	CPF VARCHAR(11),
	[Status] VARCHAR(128)
)

CREATE TABLE VENDA
(
	IdVenda INT IDENTITY PRIMARY KEY,
	IdCliente VARCHAR(128),
	[Data] DATE,
	Tipo VARCHAR(128)
)

CREATE TABLE ITENS
(
    IdItens INT IDENTITY PRIMARY KEY, 
	IdVenda INT, 
	IdProduto INT, 
	Quantidade INT,
	Valor FLOAT
)

CREATE TABLE PRODUTO
(
	IdProduto INT IDENTITY PRIMARY KEY,
	Descricao VARCHAR(128),
	Valor FLOAT,
	Quantidade INT,
	Unidade_Medida VARCHAR(128)
)

ALTER TABLE Venda ADD CONSTRAINT FK_Venda_Cliente FOREIGN KEY (IdCliente) REFERENCES CLIENTE(IdCliente)

ALTER TABLE Itens ADD CONSTRAINT FK_Itens_Venda FOREIGN KEY (IdVenda) REFERENCES VENDA(IdVenda)

ALTER TABLE Itens ADD CONSTRAINT FK_Itens_Produto FOREIGN KEY (IdProduto) REFERENCES PRODUTO(IdProduto)
