CREATE DATABASE CRUZEIRODOSUL

CREATE TABLE TB_PAIS
(
	ID_PAIS INT IDENTITY PRIMARY KEY,
	NM_PAIS VARCHAR(100),
	NR_POPULACAO INT
)

CREATE TABLE TB_CIRCUITO
(
	ID_CIRCUITO INT IDENTITY PRIMARY KEY,
	NM_CIRCUITO VARCHAR(100),
	NR_EXTENSAO INT,
	ID_PAIS INT CONSTRAINT FK_CIRCUITO_PAIS FOREIGN KEY (ID_PAIS) REFERENCES TB_PAIS(ID_PAIS)
)

CREATE TABLE TB_PROVA
(
	ID_PROVA INT IDENTITY PRIMARY KEY,
	DT_PROVA DATE,
	NM_SITUACAO VARCHAR(100),
	ID_CIRCUITO INT CONSTRAINT FK_PROVA_CIRCUITO FOREIGN KEY (ID_CIRCUITO) REFERENCES TB_CIRCUITO(ID_CIRCUITO)
)

CREATE TABLE TB_PILOTO
(
	ID_PILOTO INT IDENTITY PRIMARY KEY,
	NM_PILOTO VARCHAR(100),
	DT_NASCIMENTO Date,
	ID_PAIS INT CONSTRAINT FK_PILOTO_PAIS FOREIGN KEY (ID_PAIS) REFERENCES TB_PAIS(ID_PAIS),
	ID_EQUIPE INT
)

CREATE TABLE TB_RESULTADO
(
	ID_PROVA INT CONSTRAINT FK_RESULTADO_PROVA FOREIGN KEY (ID_PROVA) REFERENCES TB_PROVA(ID_PROVA),
	ID_PILOTO INT CONSTRAINT FK_RESULTADO_PILOTO FOREIGN KEY (ID_PILOTO) REFERENCES TB_PILOTO(ID_PILOTO),
	NR_TEMPO_PROVA FLOAT,
	NR_COLOC_FINAL INT,
	NR_POSICAO_GRID INT,
	NR_MELHOR_VOLTA INT
)

CREATE TABLE TB_EQUIPE
(
	ID_EQUIPE INT IDENTITY PRIMARY KEY,
	NM_EQUIPE VARCHAR(100),
	ID_PAIS INT CONSTRAINT FK_EQUIPE_PAIS FOREIGN KEY (ID_PAIS) REFERENCES TB_PAIS(ID_PAIS)
)

--DROP TABLE TB_RESULTADO 
--DROP TABLE TB_PILOTO
--DROP TABLE TB_EQUIPE
--DROP TABLE TB_PAIS
--DROP TABLE TB_CIRCUITO
--DROP TABLE TB_PROVA

INSERT INTO TB_PAIS (NM_PAIS, NR_POPULACAO) VALUES ('BRASIL', 500000000)
INSERT INTO TB_PAIS (NM_PAIS, NR_POPULACAO) VALUES ('ARGENTINA', 100000000)
INSERT INTO TB_CIRCUITO (NM_CIRCUITO, NR_EXTENSAO, ID_PAIS) VALUES ('INDIANAPOLIS', 547175314, 1)
INSERT INTO TB_EQUIPE (NM_EQUIPE, ID_PAIS) VALUES ('MCLAREN', 1)
INSERT INTO TB_PILOTO (NM_PILOTO, DT_NASCIMENTO, ID_PAIS, ID_EQUIPE) VALUES ('AYRTON SENNA', '1992-08-12', 1, 1)
INSERT INTO TB_PROVA (DT_PROVA, NM_SITUACAO) VALUES ('2022-08-08', 'RISCO DE CHUVA')
INSERT INTO TB_RESULTADO (ID_PILOTO, NR_TEMPO_PROVA, NR_COLOC_FINAL, NR_POSICAO_GRID, NR_MELHOR_VOLTA) VALUES (1, 37895, 1, 1, 3)
INSERT INTO TB_PAIS (NM_PAIS, NR_POPULACAO) VALUES ('EUA', 356200000)
INSERT INTO TB_PAIS (NM_PAIS, NR_POPULACAO) VALUES ('MARROCOS', 22000000)
INSERT INTO TB_PAIS (NM_PAIS, NR_POPULACAO) VALUES ('CANADA', 410000000)